services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db  # Changed to named volume (better persistence)
    ports:
      - "27017:27017"
    restart: unless-stopped  # Added auto-restart

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile  # Explicit Dockerfile path
    env_file:
      - ./backend/.env  # Changed to standard .env filename
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env  # Changed to standard .env filename
    ports:
      - "5173:5173"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.0.5-alpine 
    ports:  # Changed expose to ports for external access
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo_data:  # Named volume for MongoDB
