services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:  # Directly defined environment variables
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/wanderlust
      - NODE_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:  # Directly defined environment variables
      - VITE_API_URL=http://localhost:5000
      - VITE_MAPBOX_TOKEN=your_mapbox_token_here
    ports:
      - "5173:5173"
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.0.5-alpine 
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mongo_data:
